export const SET_DARK_THEME = 'SET_DARK_THEME'

export const FETCH_ANIME_LIST = 'FETCH_ANIME_LIST'
export const SET_ANIME_LIST_LOADED = 'SET_ANIME_LIST_LOADED'

export const FETCH_ANIME_INFO = 'FETCH_ANIME_INFO'
export const SET_ANIME_INFO_LOADED = 'SET_ANIME_INFO_LOADED'

export const FETCH_NEWS = 'FETCH_NEWS'
export const SET_NEWS_LOADED = 'SET_NEWS_LOADED'

export const FETCH_ANIME = 'FETCH_ANIME'
export const SET_ANIME_LOADED = 'SET_ANIME_LOADED'

export const FETCH_ANIME_EPISODE = 'FETCH_ANIME_EPISODE'
export const SET_ANIME_EPISODE_LOADED = 'SET_ANIME_EPISODE_LOADED'
