export const SET_DARK_THEME = 'SET_DARK_THEME'

export const FETCH_NEWS = 'FETCH_NEWS'
export const SET_NEWS_LOADING = 'SET_NEWS_LOADING'
export const SET_NEWS_ERROR = 'SET_NEWS_ERROR'

export const FETCH_ANIME_LIST = 'FETCH_ANIME_LIST'
export const SET_ANIME_LIST_LOADING = 'SET_ANIME_LIST_LOADING'
export const SET_ANIME_LIST_ERROR = 'SET_ANIME_LIST_ERROR'

export const FETCH_ANIME_INFO = 'FETCH_ANIME_INFO'
export const SET_ANIME_INFO_LOADING = 'SET_ANIME_INFO_LOADING'
export const SET_ANIME_INFO_ERROR = 'SET_ANIME_INFO_ERROR'

export const FETCH_ANIME = 'FETCH_ANIME'
export const SET_ANIME_LOADING = 'SET_ANIME_LOADING'
export const SET_ANIME_ERROR = 'SET_ANIME_ERROR'

export const FETCH_ANIME_EPISODE = 'FETCH_ANIME_EPISODE'
export const SET_ANIME_EPISODE_LOADING = 'SET_ANIME_EPISODE_LOADING'
export const SET_ANIME_EPISODE_ERROR = 'SET_ANIME_EPISODE_ERROR'
